[2022-11-27 19:32:40] local.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Compilers\\Compiler.php:36)
[stacktrace]
#0 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\ViewServiceProvider.php(88): Illuminate\\View\\Compilers\\Compiler->__construct(Object(Illuminate\\Filesystem\\Filesystem), false)
#1 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(873): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(758): Illuminate\\Container\\Container->build(Object(Closure))
#3 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(851): Illuminate\\Container\\Container->resolve('blade.compiler', Array, true)
#4 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(694): Illuminate\\Foundation\\Application->resolve('blade.compiler', Array)
#5 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(836): Illuminate\\Container\\Container->make('blade.compiler', Array)
#6 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1419): Illuminate\\Foundation\\Application->make('blade.compiler')
#7 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\ViewServiceProvider.php(150): Illuminate\\Container\\Container->offsetGet('blade.compiler')
#8 [internal function]: Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#9 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\EngineResolver.php(55): call_user_func(Object(Closure))
#10 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(467): Illuminate\\View\\Engines\\EngineResolver->resolve('blade')
#11 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(158): Facade\\Ignition\\IgnitionServiceProvider->hasCustomViewEnginesRegistered()
#12 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(101): Facade\\Ignition\\IgnitionServiceProvider->registerViewEngines()
#13 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Facade\\Ignition\\IgnitionServiceProvider->boot()
#14 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#16 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(924): Illuminate\\Container\\Container->call(Array)
#19 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(905): Illuminate\\Foundation\\Application->bootProvider(Object(Facade\\Ignition\\IgnitionServiceProvider))
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Facade\\Ignition\\IgnitionServiceProvider), 15)
#21 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(906): array_walk(Array, Object(Closure))
#22 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#23 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#24 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#25 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#26 C:\\xampp\\htdocs\\server\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 {main}
"} 
[2022-11-27 19:32:50] local.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Compilers\\Compiler.php:36)
[stacktrace]
#0 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\ViewServiceProvider.php(88): Illuminate\\View\\Compilers\\Compiler->__construct(Object(Illuminate\\Filesystem\\Filesystem), false)
#1 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(873): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(758): Illuminate\\Container\\Container->build(Object(Closure))
#3 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(851): Illuminate\\Container\\Container->resolve('blade.compiler', Array, true)
#4 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(694): Illuminate\\Foundation\\Application->resolve('blade.compiler', Array)
#5 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(836): Illuminate\\Container\\Container->make('blade.compiler', Array)
#6 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1419): Illuminate\\Foundation\\Application->make('blade.compiler')
#7 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\ViewServiceProvider.php(150): Illuminate\\Container\\Container->offsetGet('blade.compiler')
#8 [internal function]: Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#9 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\EngineResolver.php(55): call_user_func(Object(Closure))
#10 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(467): Illuminate\\View\\Engines\\EngineResolver->resolve('blade')
#11 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(158): Facade\\Ignition\\IgnitionServiceProvider->hasCustomViewEnginesRegistered()
#12 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(101): Facade\\Ignition\\IgnitionServiceProvider->registerViewEngines()
#13 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Facade\\Ignition\\IgnitionServiceProvider->boot()
#14 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#16 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(924): Illuminate\\Container\\Container->call(Array)
#19 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(905): Illuminate\\Foundation\\Application->bootProvider(Object(Facade\\Ignition\\IgnitionServiceProvider))
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Facade\\Ignition\\IgnitionServiceProvider), 16)
#21 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(906): array_walk(Array, Object(Closure))
#22 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#23 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#24 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#25 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#26 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 {main}
"} 
[2022-11-27 19:32:50] local.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Compilers\\Compiler.php:36)
[stacktrace]
#0 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\ViewServiceProvider.php(88): Illuminate\\View\\Compilers\\Compiler->__construct(Object(Illuminate\\Filesystem\\Filesystem), false)
#1 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(873): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(758): Illuminate\\Container\\Container->build(Object(Closure))
#3 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(851): Illuminate\\Container\\Container->resolve('blade.compiler', Array, true)
#4 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(694): Illuminate\\Foundation\\Application->resolve('blade.compiler', Array)
#5 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(836): Illuminate\\Container\\Container->make('blade.compiler', Array)
#6 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1419): Illuminate\\Foundation\\Application->make('blade.compiler')
#7 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\ViewServiceProvider.php(150): Illuminate\\Container\\Container->offsetGet('blade.compiler')
#8 [internal function]: Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#9 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\EngineResolver.php(55): call_user_func(Object(Closure))
#10 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(467): Illuminate\\View\\Engines\\EngineResolver->resolve('blade')
#11 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(158): Facade\\Ignition\\IgnitionServiceProvider->hasCustomViewEnginesRegistered()
#12 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(101): Facade\\Ignition\\IgnitionServiceProvider->registerViewEngines()
#13 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Facade\\Ignition\\IgnitionServiceProvider->boot()
#14 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#16 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(924): Illuminate\\Container\\Container->call(Array)
#19 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(905): Illuminate\\Foundation\\Application->bootProvider(Object(Facade\\Ignition\\IgnitionServiceProvider))
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Facade\\Ignition\\IgnitionServiceProvider), 16)
#21 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(906): array_walk(Array, Object(Closure))
#22 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#23 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#24 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#25 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#26 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 {main}
"} 
[2022-11-27 19:32:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:32:54] local.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Compilers\\Compiler.php:36)
[stacktrace]
#0 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\ViewServiceProvider.php(88): Illuminate\\View\\Compilers\\Compiler->__construct(Object(Illuminate\\Filesystem\\Filesystem), false)
#1 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(873): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(758): Illuminate\\Container\\Container->build(Object(Closure))
#3 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(851): Illuminate\\Container\\Container->resolve('blade.compiler', Array, true)
#4 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(694): Illuminate\\Foundation\\Application->resolve('blade.compiler', Array)
#5 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(836): Illuminate\\Container\\Container->make('blade.compiler', Array)
#6 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1419): Illuminate\\Foundation\\Application->make('blade.compiler')
#7 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\ViewServiceProvider.php(150): Illuminate\\Container\\Container->offsetGet('blade.compiler')
#8 [internal function]: Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#9 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\EngineResolver.php(55): call_user_func(Object(Closure))
#10 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(467): Illuminate\\View\\Engines\\EngineResolver->resolve('blade')
#11 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(158): Facade\\Ignition\\IgnitionServiceProvider->hasCustomViewEnginesRegistered()
#12 C:\\xampp\\htdocs\\server\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(101): Facade\\Ignition\\IgnitionServiceProvider->registerViewEngines()
#13 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Facade\\Ignition\\IgnitionServiceProvider->boot()
#14 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#16 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(924): Illuminate\\Container\\Container->call(Array)
#19 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(905): Illuminate\\Foundation\\Application->bootProvider(Object(Facade\\Ignition\\IgnitionServiceProvider))
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Facade\\Ignition\\IgnitionServiceProvider), 15)
#21 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(906): array_walk(Array, Object(Closure))
#22 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#23 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#24 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#25 C:\\xampp\\htdocs\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#26 C:\\xampp\\htdocs\\server\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 {main}
"} 
[2022-11-27 19:33:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:34:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:35:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:36:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:37:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:38:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:39:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:40:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:41:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:42:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:43:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:44:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:45:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:46:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:47:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:48:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:49:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:50:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:51:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:52:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:53:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:54:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:55:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:56:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:57:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:58:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 19:59:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:00:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:01:57] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:02:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:03:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:04:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:05:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:06:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:07:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:08:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:09:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:10:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:11:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:12:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:13:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:14:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:15:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:16:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:17:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:18:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:19:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:20:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:21:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:22:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:23:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:24:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:25:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:26:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:27:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:28:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:29:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:30:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:31:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:32:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:33:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:34:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:35:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:36:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:37:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:38:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:39:50] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:40:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:41:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:42:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:43:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:44:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:45:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:46:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:47:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:48:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:49:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:50:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:51:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:52:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:53:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:54:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:55:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:56:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:57:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:58:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 20:59:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:00:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:01:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:02:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:03:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:04:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:05:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:06:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:07:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:08:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:09:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:10:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:11:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:12:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:13:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:14:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:15:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:16:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:17:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:18:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:19:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:20:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:21:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:22:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:23:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:24:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:25:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:26:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:27:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:28:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:29:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:30:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:31:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:32:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:33:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:34:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:35:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:36:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:37:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:38:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:39:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:40:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
[2022-11-27 21:41:51] local.ERROR: Cannot redeclare responseSuccess() (previously declared in C:\xampp\htdocs\server\app\Helper.php:6) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare responseSuccess() (previously declared in C:\\xampp\\htdocs\\server\\app\\Helper.php:6) at C:\\xampp\\htdocs\\server\\app\\Helper.php:6)
[stacktrace]
#0 {main}
"} 
